Patch "localeCompare" bug caused due to inconsitent year type
We are seeing some users get `TypeError: e.year.localeCompare is not a function` error occasionally. This is likely due to mismatch types. Year is stored as a string or a number in the database, which is not ideal but this patches the issue